### ISSUE TITLE
Fix: allow standalone execution of modules

### ISSUE THREAD

**Issue by wanysteus** [planet-learning/planet-learning#22]
Currently (after #13) the modules use variables declared in `main.py` in order to run but the `if __name__ == '__main__':` section has not been updated to deal with this comportement

**Comment by proxyma-centauri** [comment]
What do you want to do exactly? update the if ... section of catascript and extrattic? I do not really see the point as #20 should provide enough leeway so that we do not have to run the modules individually outside of main (with at least a "RE_LAUNCH" boolean like for catascript.

the simpler thing on this issue could be to just delete the ```if __name__ ``` blocks that are still present in the code

**Comment by wanysteus** [comment]
I'm ok with that solution. Will do it asap!
